version: 2.1
orbs:
  node: circleci/go@1.7.0
  slack: circleci/slack@4.4.2

jobs:
  build:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: go build
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: '@9rum'
  test:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: '@9rum'

workflows:
  version: 2
  ci:
    jobs:
      - build
      - test:
          requires:
            - build
