
PUT http://localhost:3000/api/v1/activity/applyp HTTP/1.1
Content-Type: application/json

{
  "_id": "610d4cfa567af2cc318e7f97",
  "member_id": "20172227"
  
}

###

GET  http://localhost:3000/api/v1/activity/papplies HTTP/1.1
Content-Type: application/json

{
  "_id": "610d4cfa567af2cc318e7f97"
  
}

###

PUT  http://localhost:3000/api/v1/activity/approvep HTTP/1.1
Content-Type: application/json

{
  "_id": "610d4cfa567af2cc318e7f97",
  "member_ids": [
    "20172229",
    "20171718"
  ]
  
}

###

PUT  http://localhost:3000/api/v1/activity/rejectp HTTP/1.1
Content-Type: application/json

{
  "_id": "610d4cfa567af2cc318e7f97",
  "member_ids": [
    "20172228",
    "20171718"
  ]
  
}

###

PUT   http://localhost:3000/api/v1/activity/cancelp HTTP/1.1
Content-Type: application/json

{
  "_id": "610d4cfa567af2cc318e7f97",
  "member_id": "20172227"

}

###