POST http://127.0.0.1:3000/api/v1/activity/search HTTP/1.1
Content-Type: application/json

{
  "filter": {
    "type": "study"
  }
}

###

POST http://127.0.0.1:3000/api/v1/activity/update HTTP/1.1
Content-Type: application/json

{
  "update": {
    "_id": "610d458b79e122ea1d150cd6",
    "description": "Good"
  }
}

###

POST http://127.0.0.1:3000/api/v1/activity/delete HTTP/1.1
Content-Type: application/json

{
  "_id": "610d458b79e122ea1d150cd4"

}

###

POST http://127.0.0.1:3000/api/v1/activity/participants HTTP/1.1
Content-Type: application/json

{
  "_id": "610d458b79e122ea1d150cd3"
}