POST http://127.0.0.1:3000/api/v1/member/signin HTTP/1.1
Content-Type: application/json

{
  "id": "20190002",
  "password": "asdf5678"
}

###

POST http://127.0.0.1:3000/api/v1/member/signup HTTP/1.1
Content-Type: application/json

{
  "id": "20210021",
  "name": "Kim",
  "department": "CSE",
  "phone": "010-2021-0021",
  "email": "testmail0",
  "grade": 1,
  "attendance": 0
}

###

GET http://127.0.0.1:3000/api/v1/member/signups HTTP/1.1

###

PUT http://127.0.0.1:3000/api/v1/member/approve HTTP/1.1
Content-Type: application/json

{
  "ids": [
    "20160004",
    "20210021"
  ]
}

###

PUT http://127.0.0.1:3000/api/v1/member/exit HTTP/1.1
Content-Type: application/json

{
  "id": "20210021"
}

###

GET http://127.0.0.1:3000/api/v1/member/exits HTTP/1.1

###

DELETE http://127.0.0.1:3000/api/v1/member/delete HTTP/1.1
Content-Type: application/json

{
  "ids": [
    "20210021"
  ]
}

###

POST http://127.0.0.1:3000/api/v1/member/my HTTP/1.1
Content-Type: application/json

{
  "id": "20190002",
  "password": "12345678"
}

###

GET http://127.0.0.1:3000/api/v1/member/search?query=2021 HTTP/1.1

###

PUT http://127.0.0.1:3000/api/v1/member/update HTTP/1.1
Content-Type: application/json

{
  "id": "20190002",
  "update": {
    "department": "CSE",
    "password": "12345678"
  }
}

###

GET http://127.0.0.1:3000/api/v1/member/active HTTP/1.1

###

PUT  http://127.0.0.1:3000/api/v1/member/activate HTTP/1.1
Content-Type: application/json

{
  "activate": true
}

###

GET http://127.0.0.1:3000/api/v1/member/graduates HTTP/1.1